config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :students, except: :show
  resources :courses do
    resources :enrollments, only: %i[new create destroy]
    resources :tests, except: %i[index show]
  end
  resources :assistances, only: %i[create destroy update]

  root 'courses#index'
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true
  validates :lastname, presence: true
  validates :identification, presence: true
  validates :identification, uniqueness: true
  validates :identification, numericality: { only_integer: true,
                                             greater_than: 0 }
  validates :number, presence: true
  validates :number, uniqueness: true
  validates :number, format: { with: /\A\d+\/\d\z/ }
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with:
                       /\A[a-zA-Z0-9_\-.]+@[a-zA-Z0-9_\-]+\.[a-zA-Z0-9\-.]+\z/ }

  scope :all_except, ->(user) { where.not(id: user) }

  def to_label
    "#{full_name} (#{identification})"
  end

  def full_name
    "#{lastname}, #{name}"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_student, only: %i[edit update destroy]

  # GET /students
  def index
    @students = Student.all
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit; end

  # POST /students
  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to students_url, notice: 'Student was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /students/1
  def update
    if @student.update(student_params)
      redirect_to @student, notice: 'Student was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /students/1
  def destroy
    @student.destroy
    redirect_to students_url, notice: 'Student was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def student_params
    params.require(:student).permit(:name, :lastname, :identification, :number, :email)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= simple_form_for(@student) do |f| %>
    <%= f.input :name %>
    <%= f.input :lastname %>
    <%= f.input :identification %>
    <%= f.input :number %>
    <%= f.input :email, as: :email %>

  <div class="form-actions text-right">
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

app/views/students/_layout.html.erb
<div class="page-header">
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb">
            <%= yield :breadcrumb %>
        </ol>
    </nav>
    <h1>
        <%= t 'students.title' %>
    </h1>
</div>

<%= yield :content %>

app/views/students/edit.html.erb
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item" aria-current="page">
    <%= link_to courses_path do %>
      <i class="material-icons">school</i>
      <%= t "students.title" %>
    <% end %>
  </li>
  <li class="breadcrumb-item" aria-current="page">
    <%= @student.lastname %>, <%= @student.name %>
  </li>
  <li class="breadcrumb-item active" aria-current="page">
    <%= t("breadcrumbs.edit") %> 
  </li>
<% end %>

<% content_for :content do %>

  <div class="row">
    <div class="col col-md-8 col-lg-6 col-xl-5">
      <div class="card">
        <div class="card-body">
          <%= render 'form', course: @course %>
        </div>
      </div>
    </div>
  </div>

<% end %>

<%= render "layout" %>

app/views/students/index.html.erb
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item active" aria-current="page">
    <i class="material-icons">contacts</i>
    <%= t 'students.title' %>
  </li>
<% end %>

<% content_for :content do %>
  <div class="card">
    <div class="card-body">
      <%= link_to t('students.add'), new_student_path, class: "btn btn-primary"  %>
    </div>
    <div class="card-body">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th><%= t 'students.name' %></th>
            <th><%= t 'students.lastname' %></th>
            <th><%= t 'students.identification' %></th>
            <th><%= t 'students.number' %></th>
            <th><%= t 'students.actions' %></th>
          </tr>
        </thead>
        <tbody>
        <% @students.each do |student| %>
          <tr>
            <td><%= student.name %></td>
            <td><%= student.lastname %></td>
            <td><%= student.identification %></td>
            <td><%= student.number %></td>
            <td>
              <%= link_to t('edit'), edit_student_path(student) %>
              <%= link_to t('destroy'), student, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>
<%= render "layout" %>

app/views/students/new.html.erb
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item" aria-current="page">
    <%= link_to students_path do %>
      <i class="material-icons">school</i>
      <%= t "students.title" %>
    <% end %>
  </li>
  <li class="breadcrumb-item active" aria-current="page">
    <%= t("breadcrumb.new") %> 
  </li>
<% end %>

<% content_for :content do %>

  <div class="row">
    <div class="col col-md-8 col-lg-6 col-xl-4">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= t 'students.new' %></h4>
          <%= render 'form', course: @student %>
        </div>
      </div>
    </div>
  </div>

<% end %>


<%= render "layout" %>